# Generated by Django 4.1.3 on 2023-04-17 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to=server.models.cult_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(upload_to=server.models.post_handler)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
                ('likes', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.models.menu_handler)),
                ('start', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='SportInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to=server.models.sport_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollNumber', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('roomNumber', models.CharField(max_length=3)),
                ('photo', models.ImageField(default='default.jpg', upload_to=server.models.image_handler)),
            ],
            options={
                'ordering': ['roomNumber'],
            },
        ),
        migrations.CreateModel(
            name='TechInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to=server.models.tech_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('por', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.student')),
            ],
        ),
    ]
