# Generated by Django 4.1.3 on 2023-04-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_meal_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='details',
            field=models.TextField(default='Empty'),
        ),
        migrations.AddField(
            model_name='student',
            name='RFID',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
