# Generated by Django 4.1.3 on 2023-04-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_complaint_details_student_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
