# Generated by Django 4.1.3 on 2023-04-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
