# Generated by Django 4.1.3 on 2023-04-19 13:49

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_event_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='council',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=server.models.council_handler),
        ),
        migrations.AddField(
            model_name='council',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='details',
            field=models.TextField(default='default.jpg'),
        ),
    ]
