# Generated by Django 4.1.3 on 2023-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_event_options_council_image_council_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='student',
        ),
        migrations.AddField(
            model_name='council',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
