# Generated by Django 4.1.3 on 2023-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_remove_council_student_council_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='council',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
