# Generated by Django 4.1.3 on 2023-05-03 11:27

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_council_mobile_alter_council_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelConstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.models.constitution_handler)),
            ],
        ),
    ]
