# Generated by Django 4.1.3 on 2023-05-03 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_hostelconstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelconstitution',
            name='amended',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
